name: Build NURI EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build EXE
      run: python build_exe.py
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4  # ← v3 dan v4 ga
      with:
        name: NURI-EXE
        path: dist/NURI.exe
        retention-days: 90
